name: 'Upload Hotspot report to BigQuery'
description: 'Formats and inserts a new hotspot detection report to BigQuery'
inputs:
  projectId:
    description: 'The target BigQuery project id'
    required: true
  datasetId:
    description: 'The target BigQuery dataset id'
    required: true
  tableId:
    description: 'The target BigQuery table id'
    required: true
  jsonFilePath:
    description: 'Path and filename of the JSON file to insert'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
