name: 'Upload Hotspot report to BigQuery'
description: 'Formats and inserts a new hotspot detection report to BigQuery'
inputs:
  application_credentials:
    description: 'application_credentials'
    required: true
  projectId:
    description: 'projectId'
    required: true
  datasetId:
    description: 'datasetId'
    required: true
  tableId:
    description: 'tableId'
    required: true
  reportFilename:
    description: 'Report filename'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
